mysite/about/urls.py
# from django.urls import re_path, include
from django.urls import path
from .views import aboutView

urlpatterns = [
    path('about/', aboutView, name='about'),
]

mysite/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
]

mysite/contact/urls.py
from django.urls import path
from .views import contactView

urlpatterns = [
    path('', contactView, name='contact'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('contact/contact/', include('contact.urls')),
    path('about/', include('about.urls')),
    path('tinymce/', include('tinymce.urls')),
]

mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User


STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    brief = models.CharField(max_length=200, unique=False, default='...')
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    cover_image = models.CharField(max_length=50, default='')
    ready = models.IntegerField(choices=STATUS,default=0)


    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

mysite/blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

mysite/about/views.py
from django.shortcuts import render


def aboutView(request):
    template_name='about.html'
    return render(request, 'about/about.html')

mysite/blog/views.py
from django.views import generic
from .models import Post, Comment
from .forms import CommentForm
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from . import urls

class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/home.html'


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    # List of active comments for this post
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', post.slug)

    comments = post.comments.filter(active=True)
    new_comment = None
    form = CommentForm()

    return render(request, 'blog/post_detail.html', {'post': post,
                                           'comments': comments,
                                           'form': form})

mysite/contact/views.py
from django.shortcuts import render

def contactView(request):
    template_name='contact.html'
    return render(request, 'contact/contact.html')

mysite/about/templates/about/about.html
{% extends "about/header.html" %}

{% block content %}
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blogcss/style2.css' %}">
</head>


<body>
    <div class="col-md-8 col-md-10 mx-auto">
        <h2 class="text-center">Hi, I'm Holly...</h2>
        <img src="{% static 'images/aboutme.jpg' %}" alt="" class="img-responsive" id="about">
        <br>
        <p class="text-dark">I am a recent engineering grad with plans to soul search on a gap year before entering 50 odd years of work. One month into my adventures I found myself quarantined in a hostel in South America, unsure when travel restrictions might be lifted. I returned to my family home and with the suggestion to write a blog, a wave of enthusiasm washed over me... and that brings us to the present day. I learned to develop a website and now I'm writing an about me page.
            <br>
        I will be reflecting on life events, aiming to gain some clarity in the chaos of the world. I intend to be open and honest when sharing my perspectives. My hope is that this hobby might spark some discussion and that we will learn something new. Here's to discovery!
        </p>
    </div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

{% endblock %}

mysite/about/templates/about/header.html
<!DOCTYPE html>
<html lang='en'>

<head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Holly Mother of Blog</title>
</head>

<body class='body' style='background-colour:#f6f6f6f6'>

      <!-- Navigation -->
 <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">Holly Mother of Blog</a>
      <ul  class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}" >Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}" >About</a>
        </li>
      </ul>
    </div>
  </nav>
  <hr>


    {% block content %}
    {% endblock %}


<!--
<footer>
  Copyright &copy; 2020 Holly Mother of Blog| Holly George-Samuels
</footer> -->


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

</html>

mysite/blog/templates/blog/header.html
<!DOCTYPE html>
<html lang='en'>

<head>
    {% load static %}
    {% load sorl_thumbnail %}
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'blogcss/style2.css' %}"
</head>

<body class='body' style='background-colour:#f6f6f6f6'>

      <!-- Navigation bg-white-->
 <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">Holly Mother of Blog</a>

        {% thumbnail "static/images/logo.png" "100x100" crop="center" as im %}
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
    {% endthumbnail %}

      <ul  class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}" >Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}" >About</a>
        </li>
      </ul>
    </div>
  </nav>


    {% block content %}
    {% endblock %}



<!-- <footer>
  Copyright &copy; 2020 Holly Mother of Blog| Holly George-Samuels
</footer> -->


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

</html>

mysite/blog/templates/blog/home.html
{% extends "blog/header.html" %}

{% block content %}

<head>
    {% load static %}
        <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blogcss/style2.css' %}"
</head>



<body id="home">
    <header>
        <div class="container-fluid">
            <div class="top">
                <div class="thumbnail">
                    <img src="{% static 'images/bluebells.jpg' %}" alt="" class="img-responsive">
                    <div class="caption">
                        <h1>Welcome to the home of <br> Holly Mother of Blog</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <br>
    <h2 class="text-center">Blog Posts</h2>
    <br>
    <br>
    <div class="container-fluid">
        <!-- Blog Entries Column -->
        {% for post in post_list %}
        {% if post.ready == 1 %}
            <div class="card">
                <img src="{% static '' %}{{post.cover_image}}" class="card-img-top" alt="">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.brief}}</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="stretched-link">Read More...</a>
                </div>
            </div>
        {% endif %}
        {% endfor %}
    </div>
    <br>
    <h2 class="text-center">Coming soon...</h2>
    <br>
    <br>
    <div class="container-fluid">
        <!-- Blog Entries Column -->
        {% for post in post_list %}
        {% if post.ready == 0 %}
            <div class="card">
                <img src="{% static '' %}{{post.cover_image}}" class="card-img-top" alt="">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text">{{post.brief}}</p>
                </div>
            </div>
        {% endif %}
        {% endfor %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

{% endblock %}

mysite/blog/templates/blog/post_detail.html
{% extends 'blog/header.html' %}
{% block content %}

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blogcss/style2.css' %}">
</head>

<body>
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-10 mx-auto">
        <br>
        <br>
        <br>
        <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
        <p class="text-faded">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text">{{ post.content | safe}}</p>
      </div>
    </div>
  </div>
  <hr>

  <div class="container">
    <div id="add_comment">
      <div class="container">
        <form method="POST" class="post-form">
          <h3>New comment</h3>
          {% csrf_token %}
          <h6>Name: </h6>
          {{ form.name }}
          <h6>Email (your email will never be shared with anyone else): </h6>
          {{ form.email }}
          <h6>Comment: </h6>
          {{ form.body }}

          <button type="submit" class="save btn btn-primary">Send</button>
        </form>
      </div>
      <br>
          <h3>Comments</h3>
      <br>
      {% for comment in post.comments.all %}
        <div class="comment">
          <div class="date">{{ comment.created_on }}</div>
          <strong>{{ comment.name|capfirst }}</strong>
          <p>{{ comment.body|linebreaks }}</p>
        </div>
      <hr>
      {% empty %}
          <p>No comments here yet</p>
      {% endfor %}
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>


{% endblock %}

mysite/contact/templates/contact/contact.html
{% extends 'blog/header.html' %}

{% block content %}

<head>
  {% load static %}
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'blogcss/style2.css' %}">
</head>

<body id="home">
        <div class="container-fluid">
            <div class="top">
                <div class="thumbnail">
                    <img src="{% static 'images/rainbow.jpg' %}" alt="" class="img-responsive">
                    <div class="caption">
                        <h1>Get in touch!</h1>
                        <h3>Questions and suggestions are warmly welcome.</h3>
                    </div>
                </div>
            </div>
        </div>


  <div class="container">
    <div class="blog">
      <div style="text-align: center">
        <br>
        Contact email:   hollygs96@live.co.uk
      <br>    <br>
    GitHub:   github.com/HollyGS
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>


{% endblock %}

mysite/contact/templates/contact/header.html
<!DOCTYPE html>
<html lang='en'>

<head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Holly Mother of Blog</title>
</head>

<body>
      <!-- Navigation -->
 <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
  <div class="container">
    <a class="navbar-brand" href="index.html">Holly Mother of Blog</a>
      <ul  class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}" >Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}" >About</a>
        </li>
      </ul>
    </div>
  </nav>


    {% block content %}
    {% endblock %}






    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

</html>